require_relative 'parser'

class NestCodeGen
  def initialize(ast, output_path)
    @ast = ast
    @output_path = output_path
    @heap_offset = 0
    @output_lines = []
    @globals = {}
    @global_offset = 32
    @next_global = 0
    @label_counter = 0
    @current_function = nil
    @locals = {}
    @next_local = 0
    @function_locals = {}
    @param_count = 0
    @string_literals = [] 
    @string_initialization = []
    @global_initialization = []
  end

  def generate
    @output_lines << "; Generated by Nest compiler"
    @output_lines << ".NVM0"
    @output_lines << ""
    
    collect_strings_and_globals(@ast)

    global_memory_size = @next_global * 4
    
    string_memory_size = calculate_string_memory_size
    total_memory = global_memory_size + string_memory_size

    heap_size = @global_offset + total_memory
    heap_size = 1 << (heap_size - 1).bit_length if heap_size > 1
    
    @output_lines << "_start:"
    @output_lines << "    ; allocate #{heap_size} bytes for heap"
    @output_lines << "    PUSH #{heap_size}"
    @output_lines << "    SYSCALL sbrk"
    @output_lines << ""

    initialize_globals_and_strings

    generate_entry_point
    @output_lines << "    JMP end"
    @output_lines << ""
    generate_functions
    @output_lines << "end:"
    @output_lines << "    PUSH 0"
    @output_lines << "    SYSCALL exit"
  
    File.write(@output_path, @output_lines.join("\n"))
  end

  private

  def collect_strings_and_globals(node)
    case node
    when NestParser::Program
      node.statements.each { |stmt| collect_strings_and_globals(stmt) }
    when NestParser::VariableDeclaration
      if @current_function.nil?
        type = infer_type(node.initializer)
        offset = @global_offset + @next_global * 4
        @globals[node.name] = { offset: offset, type: type, initialized: !!node.initializer }
        @next_global += 1
      end
      collect_strings_and_globals(node.initializer) if node.initializer
    when NestParser::FunctionDeclaration
      @function_locals[node.name] = { params: node.parameters.size, locals: 0 }
      @param_count = node.parameters.size
      collect_strings_and_globals(node.body)
    when NestParser::BlockStatement
      node.statements.each { |stmt| collect_strings_and_globals(stmt) }
    when NestParser::StringLiteral
      @string_literals << node unless @string_literals.include?(node)
    when NestParser::BinaryExpression
      collect_strings_and_globals(node.left)
      collect_strings_and_globals(node.right)
    when NestParser::UnaryExpression
      collect_strings_and_globals(node.operand)
    when NestParser::Assignment
      collect_strings_and_globals(node.value)
    when NestParser::ReturnStatement
      collect_strings_and_globals(node.value) if node.value
    when NestParser::FunctionCall
      node.arguments.each { |arg| collect_strings_and_globals(arg) }
    when NestParser::IfStatement
      collect_strings_and_globals(node.condition)
      collect_strings_and_globals(node.then_branch)
      collect_strings_and_globals(node.else_branch) if node.else_branch
    when NestParser::WhileStatement
      collect_strings_and_globals(node.condition)
      collect_strings_and_globals(node.body)
    end
  end

  def calculate_string_memory_size
    total = 0
    @string_literals.each do |str_lit|
      total += str_lit.value.length + 1 
    end
    total
  end

  def infer_type(expr)
    case expr
    when NestParser::StringLiteral then :string
    when NestParser::IntegerLiteral then :i32
    when NestParser::BooleanLiteral then :bool
    when nil then :i32
    else :i32
    end
  end

  def initialize_globals_and_strings
    @globals.each do |name, info|
      @output_lines << "    ; init global #{name}"
      var_decl = find_variable_declaration(name)
      if var_decl && var_decl.initializer
        old_function = @current_function
        @current_function = nil
        visit_expression(var_decl.initializer)
        @current_function = old_function
        @output_lines << "    PUSH #{info[:offset]}"
        @output_lines << "    STORE_ABS"
      else
        @output_lines << "    PUSH #{info[:offset]}"
        @output_lines << "    PUSH 0"
        @output_lines << "    STORE_ABS"
      end
    end
    
    if @string_literals.any?
      @output_lines << ""
      @output_lines << "    ; initialize string literals"
      string_offset = @global_offset + (@next_global * 4)
      
      @string_literals.each do |str_lit|
        str_lit.heap_offset = string_offset
        
        str_lit.value.chars.each_with_index do |ch, idx|
          @output_lines << "    PUSH #{string_offset + idx}"
          @output_lines << "    PUSH #{ch.ord}"
          @output_lines << "    STORE_HEAP"
        end
        
        # Null terminator
        @output_lines << "    PUSH #{string_offset + str_lit.value.length}"
        @output_lines << "    PUSH 0"
        @output_lines << "    STORE_HEAP"
        
        string_offset += str_lit.value.length + 1
      end
      @output_lines << ""
    end
  end

  def find_variable_declaration(name)
    @ast.statements.find do |stmt|
      stmt.is_a?(NestParser::VariableDeclaration) && stmt.name == name
    end
  end

  def new_label
    @label_counter += 1
    "label_#{@label_counter}"
  end

  def generate_entry_point
    main_func = @ast.statements.find { |s| s.is_a?(NestParser::FunctionDeclaration) && s.name == "main" }
    if main_func
      @output_lines << "    ; call main"
      @output_lines << "    CALL main"
    else
      @ast.statements.each do |stmt|
        next if stmt.is_a?(NestParser::FunctionDeclaration)
        visit_statement(stmt)
      end
    end
  end

  def generate_functions
    @ast.statements.each do |stmt|
      if stmt.is_a?(NestParser::FunctionDeclaration)
        generate_function(stmt)
      end
    end
  end

  def count_function_locals(node)
    count = 0
    case node
    when NestParser::BlockStatement
      node.statements.each do |stmt|
        if stmt.is_a?(NestParser::VariableDeclaration)
          count += 1
        elsif stmt.is_a?(NestParser::BlockStatement)
          count += count_function_locals(stmt)
        elsif stmt.is_a?(NestParser::IfStatement)
          count += count_function_locals(stmt.then_branch)
          count += count_function_locals(stmt.else_branch) if stmt.else_branch
        elsif stmt.is_a?(NestParser::WhileStatement)
          count += count_function_locals(stmt.body)
        end
      end
    end
    count
  end

  def has_return_statement(node)
    case node
    when NestParser::ReturnStatement
      true
    when NestParser::BlockStatement
      node.statements.any? { |stmt| has_return_statement(stmt) }
    else
      false
    end
  end

  def generate_function(node)
    @current_function = node.name
    @locals = {}
    @next_local = 0
    params_count = node.parameters.size

    @output_lines << ""
    @output_lines << "#{node.name}:"
    @output_lines << "    ; function #{node.name}(#{node.parameters.join(', ')})"

    local_count = count_function_locals(node.body)
    total_locals = params_count + local_count
    @function_locals[node.name][:locals] = total_locals

    @output_lines << "    ENTER #{total_locals}"

    node.parameters.each_with_index do |param, idx|
      @locals[param] = { offset: idx, type: :i32, is_param: true }
    end

    visit_block_statement(node.body)

    unless has_return_statement(node.body)
      @output_lines << "    LEAVE"
      @output_lines << "    RET"
    end

    @current_function = nil
  end

  def visit_statement(stmt)
    case stmt
    when NestParser::VariableDeclaration
      visit_variable_declaration(stmt)
    when NestParser::Assignment
      visit_assignment(stmt)
    when NestParser::IfStatement
      visit_if_statement(stmt)
    when NestParser::WhileStatement
      visit_while_statement(stmt)
    when NestParser::ReturnStatement
      visit_return_statement(stmt)
    when NestParser::FunctionCall
      visit_function_call(stmt)
    when NestParser::BlockStatement
      visit_block_statement(stmt)
    else
      raise "Unsupported statement: #{stmt.class}"
    end
  end

  def visit_block_statement(block)
    block.statements.each { |stmt| visit_statement(stmt) }
  end

  def visit_variable_declaration(node)
    if @current_function
      params_count = @function_locals[@current_function][:params]
      offset = params_count + @next_local
      @locals[node.name] = { offset: offset, type: infer_type(node.initializer), is_param: false }
      @next_local += 1

      @output_lines << "    ; local var #{node.name}"
      if node.initializer
        visit_expression(node.initializer)
        @output_lines << "    STORE_REL #{offset}"
      else
        @output_lines << "    PUSH 0"
        @output_lines << "    STORE_REL #{offset}"
      end
    else
      @output_lines << "    ; global var #{node.name} at heap[#{@globals[node.name][:offset]}]"
    end
    @output_lines << ""
  end

  def visit_assignment(node)
    @output_lines << "    ; #{node.name} = ..."
    visit_expression(node.value)

    if @current_function && @locals[node.name]
      var = @locals[node.name]
      @output_lines << "    STORE_REL #{var[:offset]}"
    elsif @globals[node.name]
      @output_lines << "    PUSH #{@globals[node.name][:offset]}"
      @output_lines << "    STORE_ABS"
    else
      raise "Undefined variable: #{node.name}"
    end
    @output_lines << ""
  end

  def visit_return_statement(node)
    @output_lines << "    ; return"
    if node.value
      visit_expression(node.value)
    else
      @output_lines << "    PUSH 0"
    end
    @output_lines << "    LEAVE"
    @output_lines << "    RET"
    @output_lines << ""
  end
  
  def visit_function_call(node)
    @output_lines << "    ; call #{node.name}"
    
    case node.name
    when "open"
      node.arguments.reverse_each do |arg|
        visit_expression(arg)
      end
      @output_lines << "    SYSCALL open"
      
    when "read"
      if node.arguments.size != 2
        raise "read expects 2 arguments: fd, offset"
      end
      
      visit_expression(node.arguments[0])
      visit_expression(node.arguments[1])
      @output_lines << "    SYSCALL read"
      
    when "write"
      if node.arguments.size != 2
        raise "write expects 2 arguments: fd, offset"
      end
      
      visit_expression(node.arguments[0])
      visit_expression(node.arguments[1])
      @output_lines << "    SYSCALL write"
    
    when "delete"
      if node.arguments.size != 1
        raise "delete expects 1 argument: path_offset"
      end
      visit_expression(node.arguments[0])
      @output_lines << "    SYSCALL remove"
    
    when "sbrk"
      if node.arguments.size != 1
        raise "sbrk expects 1 argument: increment"
      end
      
      visit_expression(node.arguments[0])
      @output_lines << "    SYSCALL sbrk"
  
    when "spawn"
      node.arguments.reverse_each do |arg|
        visit_expression(arg)
      end
      @output_lines << "    SYSCALL spawn"
  
    else
      node.arguments.reverse.each do |arg|
        visit_expression(arg)
      end
      @output_lines << "    CALL #{node.name}"
    end
  end
  
  def visit_expression(expr)
    case expr
    when NestParser::IntegerLiteral
      @output_lines << "    PUSH #{expr.value}"
    when NestParser::BooleanLiteral
      @output_lines << "    PUSH #{expr.value ? 1 : 0}"
    when NestParser::StringLiteral
      if expr.heap_offset.nil?
        raise "String literal has no heap offset assigned"
      end
      @output_lines << "    PUSH #{expr.heap_offset}"
    when NestParser::Identifier
      var_name = expr.name
      if @current_function && @locals[var_name]
        var = @locals[var_name]
        if var[:is_param]
          @output_lines << "    LOAD_ARG #{var[:offset]}"
        else
          @output_lines << "    LOAD_REL #{var[:offset]}"
        end
      elsif @globals[var_name]
        @output_lines << "    PUSH #{@globals[var_name][:offset]}"
        @output_lines << "    LOAD_ABS"
      else
        raise "Undefined variable: #{var_name}"
      end
    when NestParser::FunctionCall
      visit_function_call(expr)
    when NestParser::BinaryExpression
      case expr.operator
      when '&&', '||'
        visit_logical_binary(expr)
      else
        if string_operation?(expr)
          raise "String operations not supported. Use direct string literals."
        else
          visit_numeric_binary(expr)
        end
      end
    when NestParser::UnaryExpression
      visit_unary_expression(expr)
    else
      raise "Unsupported expression: #{expr.class}"
    end
  end

  def visit_while_statement(node)
    @output_lines << "    ; while loop"
    start_label = new_label
    end_label = new_label
    @output_lines << "#{start_label}:"
    visit_expression(node.condition)
    @output_lines << "    JZ #{end_label}"
    visit_block_statement(node.body)
    @output_lines << "    JMP #{start_label}"
    @output_lines << "#{end_label}:"
    @output_lines << "    ; end while"
    @output_lines << ""
  end

  def visit_if_statement(node)
    @output_lines << "    ; if statement"
    visit_expression(node.condition)
    else_label = new_label
    end_label = new_label
    @output_lines << "    JZ #{else_label}"
    visit_block_statement(node.then_branch)
    @output_lines << "    JMP #{end_label}"
    @output_lines << "#{else_label}:"
    if node.else_branch
      visit_block_statement(node.else_branch)
    end
    @output_lines << "#{end_label}:"
    @output_lines << "    ; end if"
    @output_lines << ""
  end

  def visit_logical_binary(node)
    if node.operator == '&&'
      false_label = new_label
      end_label = new_label
      visit_expression(node.left)
      @output_lines << "    JZ #{false_label}"
      visit_expression(node.right)
      @output_lines << "    JMP #{end_label}"
      @output_lines << "#{false_label}:"
      @output_lines << "    PUSH 0"
      @output_lines << "#{end_label}:"
    else # '||'
      true_label = new_label
      end_label = new_label
      visit_expression(node.left)
      @output_lines << "    JNZ #{true_label}"
      visit_expression(node.right)
      @output_lines << "    JMP #{end_label}"
      @output_lines << "#{true_label}:"
      @output_lines << "    PUSH 1"
      @output_lines << "#{end_label}:"
    end
  end

  def string_operation?(expr)
    return false unless expr.operator == '+'

    left_is_string = false
    right_is_string = false
    
    case expr.left
    when NestParser::StringLiteral
      left_is_string = true
    when NestParser::Identifier
      var_name = expr.left.name
      if @current_function && @locals[var_name]
        left_is_string = (@locals[var_name][:type] == :string)
      elsif @globals[var_name]
        left_is_string = (@globals[var_name][:type] == :string)
      end
    end
    
    case expr.right
    when NestParser::StringLiteral
      right_is_string = true
    when NestParser::Identifier
      var_name = expr.right.name
      if @current_function && @locals[var_name]
        right_is_string = (@locals[var_name][:type] == :string)
      elsif @globals[var_name]
        right_is_string = (@globals[var_name][:type] == :string)
      end
    end
    
    left_is_string || right_is_string
  end

  def visit_numeric_binary(node)
    visit_expression(node.left)
    visit_expression(node.right)
    case node.operator
    when '+' then @output_lines << "    ADD"
    when '-' then @output_lines << "    SUB"
    when '*' then @output_lines << "    MUL"
    when '/' then @output_lines << "    DIV"
    when '%' then @output_lines << "    MOD"
    when '<' then @output_lines << "    LT"
    when '>' then @output_lines << "    GT"
    when '<='
      @output_lines << "    GT"
      @output_lines << "    PUSH 1"
      @output_lines << "    XOR"
    when '>='
      @output_lines << "    LT"
      @output_lines << "    PUSH 1"
      @output_lines << "    XOR"
    when '=='
      @output_lines << "    EQ"
    when '!='
      @output_lines << "    EQ"
      @output_lines << "    PUSH 1"
      @output_lines << "    XOR"
    else
      raise "Unknown operator: #{node.operator}"
    end
  end

  def visit_unary_expression(node)
    visit_expression(node.operand)
    case node.operator
    when '-'
      @output_lines << "    PUSH -1"
      @output_lines << "    MUL"
    when '!'
      @output_lines << "    PUSH 1"
      @output_lines << "    XOR"
    else
      raise "Unknown unary operator: #{node.operator}"
    end
  end
end

# Add heap_offset attribute to StringLiteral nodes
class NestParser::StringLiteral
  attr_accessor :heap_offset
end