require_relative 'parser'

class NestCodeGen
  def initialize(ast, output_path)
    @ast = ast
    @output_path = output_path
    @heap_offset = 0
    @output_lines = []
    @globals = {}
    @global_offset = 1000
    @next_global = 0
    @label_counter = 0
    @current_function = nil
    @locals = {}
    @next_local = 0
    @function_locals = {}
    @param_count = 0
  end

  def generate
    @output_lines << "; Generated by Nest compiler"
    @output_lines << ".NVM0"
    @output_lines << ""
    @output_lines << "_start:"
    
    collect_globals_and_functions(@ast)
    
    if @next_global > 0
      @output_lines << "    ; global variables at heap[1000..#{999 + @next_global * 4}]"
    end
    
    generate_entry_point
    @output_lines << "    JMP end"
    @output_lines << ""
    generate_functions
    @output_lines << "end:"
    @output_lines << "    PUSH 0"
    @output_lines << "    SYSCALL exit"

    File.write(@output_path, @output_lines.join("\n"))
  end

  private

  def new_label
    @label_counter += 1
    "label_#{@label_counter}"
  end

  def collect_globals_and_functions(node)
    case node
    when NestParser::Program
      node.statements.each { |stmt| collect_globals_and_functions(stmt) }
    when NestParser::VariableDeclaration
      type = infer_type_from_initializer(node.initializer)
      @globals[node.name] = { offset: @global_offset + @next_global * 4, type: type }
      @next_global += 1
    when NestParser::FunctionDeclaration
      @function_locals[node.name] = { params: node.parameters.size, locals: 0 }
      @param_count = node.parameters.size
      collect_globals_and_functions(node.body)
    when NestParser::BlockStatement
      node.statements.each { |stmt| collect_globals_and_functions(stmt) }
    end
  end

  def infer_type_from_initializer(expr)
    case expr
    when NestParser::StringLiteral then :string
    when NestParser::IntegerLiteral then :i32
    when NestParser::BooleanLiteral then :bool
    else :i32
    end
  end

  def generate_entry_point
    main_func = @ast.statements.find { |s| s.is_a?(NestParser::FunctionDeclaration) && s.name == "main" }
    if main_func
      @output_lines << "    ; call main"
      @output_lines << "    CALL main"
    else
      @ast.statements.each do |stmt|
        next if stmt.is_a?(NestParser::FunctionDeclaration)
        visit_statement(stmt)
      end
    end
  end

  def generate_functions
    @ast.statements.each do |stmt|
      if stmt.is_a?(NestParser::FunctionDeclaration)
        generate_function(stmt)
      end
    end
  end

  def count_function_locals(node)
    count = 0
    case node
    when NestParser::BlockStatement
      node.statements.each do |stmt|
        if stmt.is_a?(NestParser::VariableDeclaration)
          count += 1
        elsif stmt.is_a?(NestParser::BlockStatement)
          count += count_function_locals(stmt)
        elsif stmt.is_a?(NestParser::IfStatement)
          count += count_function_locals(stmt.then_branch)
          count += count_function_locals(stmt.else_branch) if stmt.else_branch
        elsif stmt.is_a?(NestParser::WhileStatement)
          count += count_function_locals(stmt.body)
        end
      end
    end
    count
  end

  def has_return_statement(node)
    case node
    when NestParser::ReturnStatement
      true
    when NestParser::BlockStatement
      node.statements.any? { |stmt| has_return_statement(stmt) }
    else
      false
    end
  end

  def generate_function(node)
    @current_function = node.name
    @locals = {}
    @next_local = 0
    params_count = node.parameters.size

    @output_lines << ""
    @output_lines << "#{node.name}:"
    @output_lines << "    ; function #{node.name}(#{node.parameters.join(', ')})"

    local_count = count_function_locals(node.body)
    total_locals = params_count + local_count
    @function_locals[node.name][:locals] = total_locals

    @output_lines << "    ENTER #{total_locals}"

    node.parameters.each_with_index do |param, idx|
      @locals[param] = { offset: idx, type: :i32, is_param: true }
    end

    visit_block_statement(node.body)

    unless has_return_statement(node.body)
      @output_lines << "    LEAVE"
      @output_lines << "    RET"
    end

    @current_function = nil
  end

  def visit_statement(stmt)
    case stmt
    when NestParser::PrintStatement
      visit_print_statement(stmt)
    when NestParser::VariableDeclaration
      visit_variable_declaration(stmt)
    when NestParser::Assignment
      visit_assignment(stmt)
    when NestParser::IfStatement
      visit_if_statement(stmt)
    when NestParser::WhileStatement
      visit_while_statement(stmt)
    when NestParser::ReturnStatement
      visit_return_statement(stmt)
    when NestParser::FunctionCall
      visit_function_call(stmt)
    when NestParser::BlockStatement
      visit_block_statement(stmt)
    else
      raise "Unsupported statement: #{stmt.class}"
    end
  end

  def visit_block_statement(block)
    block.statements.each { |stmt| visit_statement(stmt) }
  end

  def visit_variable_declaration(node)
    if @current_function
      params_count = @function_locals[@current_function][:params]
      offset = params_count + @next_local
      @locals[node.name] = { offset: offset, type: infer_type_from_initializer(node.initializer), is_param: false }
      @next_local += 1

      @output_lines << "    ; local var #{node.name}"
      visit_expression(node.initializer)
      @output_lines << "    STORE_REL #{offset}"
    else
      global_info = @globals[node.name]
      @output_lines << "    ; global var #{node.name} at heap[#{global_info[:offset]}]"
      visit_expression(node.initializer)
      @output_lines << "    PUSH #{global_info[:offset]}"
      @output_lines << "    STORE_ABS"
    end
    @output_lines << ""
  end

  def visit_assignment(node)
    @output_lines << "    ; #{node.name} = ..."
    visit_expression(node.value)

    if @current_function && @locals[node.name]
      var = @locals[node.name]
      @output_lines << "    STORE_REL #{var[:offset]}"
    elsif @globals[node.name]
      @output_lines << "    PUSH #{@globals[node.name][:offset]}"
      @output_lines << "    STORE_ABS"
    else
      raise "Undefined variable: #{node.name}"
    end
    @output_lines << ""
  end

  def visit_print_statement(node)
    @output_lines << "    ; print"
    visit_expression(node.value)
    @output_lines << "    PUSH 1"
    @output_lines << "    SWAP"
    @output_lines << "    SYSCALL write"
    @output_lines << "    POP"
    @output_lines << ""
  end

  def visit_return_statement(node)
    @output_lines << "    ; return"
    if node.value
      visit_expression(node.value)
    else
      @output_lines << "    PUSH 0"
    end
    @output_lines << "    LEAVE"
    @output_lines << "    RET"
    @output_lines << ""
  end

  def visit_function_call(node)
    @output_lines << "    ; call #{node.name}"
    
    case node.name
    when "open"
      # open(path) -> fd
      # SYSCALL open expects path string offset on stack
      node.arguments.reverse_each do |arg|
        visit_expression(arg)
      end
      @output_lines << "    SYSCALL open"
      
    when "read"
      # read(fd) -> offset (string in heap)
      # SYSCALL read expects fd on stack
      node.arguments.reverse_each do |arg|
        visit_expression(arg)
      end
      @output_lines << "    SYSCALL read"
      
    when "write"
      # write(fd, offset) -> bytes written
      # SYSCALL write expects: offset, fd (in that order? let's check)
      # Actually from syscall code: offset on top (sp-1), fd at (sp-2)
      # So we need to push fd first, then offset
      if node.arguments.size != 2
        raise "write expects 2 arguments: fd, data"
      end
      
      # Push arguments in reverse order so last argument is on top
      # write(fd, data) -> we want: fd, data on stack? 
      # syscall expects: offset (top), fd (below)
      # So push fd first, then data
      visit_expression(node.arguments[0])  # fd
      visit_expression(node.arguments[1])  # data (offset)
      @output_lines << "    SYSCALL write"
      @output_lines << "    POP"  # discard bytes written
    
    when "delete"
      if node.arguments.size != 1
        raise "write expects 1 arguments: fd"
      end
      visit_expression(node.arguments[0])
      @output_lines << "  SYSCALL delete"
      @output_lines << "  POP"

    else
      # Regular function call
      node.arguments.reverse.each do |arg|
        visit_expression(arg)
      end
      @output_lines << "    CALL #{node.name}"
    end
  end

  def visit_while_statement(node)
    @output_lines << "    ; while loop"
    start_label = new_label
    end_label = new_label
    @output_lines << "#{start_label}:"
    visit_expression(node.condition)
    @output_lines << "    JZ #{end_label}"
    visit_block_statement(node.body)
    @output_lines << "    JMP #{start_label}"
    @output_lines << "#{end_label}:"
    @output_lines << "    ; end while"
    @output_lines << ""
  end

  def visit_if_statement(node)
    @output_lines << "    ; if statement"
    visit_expression(node.condition)
    else_label = new_label
    end_label = new_label
    @output_lines << "    JZ #{else_label}"
    visit_block_statement(node.then_branch)
    @output_lines << "    JMP #{end_label}"
    @output_lines << "#{else_label}:"
    if node.else_branch
      visit_block_statement(node.else_branch)
    end
    @output_lines << "#{end_label}:"
    @output_lines << "    ; end if"
    @output_lines << ""
  end

  def visit_expression(expr)
    case expr
    when NestParser::IntegerLiteral
      @output_lines << "    PUSH #{expr.value}"
    when NestParser::BooleanLiteral
      @output_lines << "    PUSH #{expr.value ? 1 : 0}"
    when NestParser::StringLiteral
      @output_lines << "    PUSH #{allocate_string(expr.value)}"
    when NestParser::Identifier
      var_name = expr.name
      if @current_function && @locals[var_name]
        var = @locals[var_name]
        if var[:is_param]
          @output_lines << "    LOAD_ARG #{var[:offset]}"
        else
          @output_lines << "    LOAD_REL #{var[:offset]}"
        end
      elsif @globals[var_name]
        @output_lines << "    PUSH #{@globals[var_name][:offset]}"
        @output_lines << "    LOAD_ABS"
      else
        raise "Undefined variable: #{var_name}"
      end
    when NestParser::FunctionCall
      visit_function_call(expr)
    when NestParser::BinaryExpression
      case expr.operator
      when '&&', '||'
        visit_logical_binary(expr)
      else
        if is_string_concatenation?(expr)
          raise "String concatenation not supported. Use separate print statements."
        else
          visit_numeric_binary(expr)
        end
      end
    when NestParser::UnaryExpression
      visit_unary_expression(expr)
    else
      raise "Unsupported expression: #{expr.class}"
    end
  end

  def visit_logical_binary(node)
    if node.operator == '&&'
      false_label = new_label
      end_label = new_label
      visit_expression(node.left)
      @output_lines << "    JZ #{false_label}"
      visit_expression(node.right)
      @output_lines << "    JMP #{end_label}"
      @output_lines << "#{false_label}:"
      @output_lines << "    PUSH 0"
      @output_lines << "#{end_label}:"
    else
      true_label = new_label
      end_label = new_label
      visit_expression(node.left)
      @output_lines << "    JNZ #{true_label}"
      visit_expression(node.right)
      @output_lines << "    JMP #{end_label}"
      @output_lines << "#{true_label}:"
      @output_lines << "    PUSH 1"
      @output_lines << "#{end_label}:"
    end
  end

  def is_string_concatenation?(expr)
    return false unless expr.operator == '+'
    left_str = string_expression?(expr.left)
    right_str = string_expression?(expr.right)
    left_str || right_str
  end

  def string_expression?(expr)
    case expr
    when NestParser::StringLiteral
      true
    when NestParser::Identifier
      if @current_function && @locals[expr.name]
        @locals[expr.name][:type] == :string
      elsif @globals[expr.name]
        @globals[expr.name][:type] == :string
      else
        false
      end
    else
      false
    end
  end

  def visit_numeric_binary(node)
    visit_expression(node.left)
    visit_expression(node.right)
    case node.operator
    when '+' then @output_lines << "    ADD"
    when '-' then @output_lines << "    SUB"
    when '*' then @output_lines << "    MUL"
    when '/' then @output_lines << "    DIV"
    when '%' then @output_lines << "    MOD"
    when '<' then @output_lines << "    LT"
    when '>' then @output_lines << "    GT"
    when '<='
      @output_lines << "    GT"
      @output_lines << "    PUSH 1"
      @output_lines << "    XOR"
    when '>='
      @output_lines << "    LT"
      @output_lines << "    PUSH 1"
      @output_lines << "    XOR"
    when '=='
      @output_lines << "    EQ"
    when '!='
      @output_lines << "    EQ"
      @output_lines << "    PUSH 1"
      @output_lines << "    XOR"
    else
      raise "Unknown operator: #{node.operator}"
    end
  end

  def visit_unary_expression(node)
    visit_expression(node.operand)
    case node.operator
    when '-'
      @output_lines << "    PUSH -1"
      @output_lines << "    MUL"
    when '!'
      @output_lines << "    PUSH 1"
      @output_lines << "    XOR"
    else
      raise "Unknown unary operator: #{node.operator}"
    end
  end

  def allocate_string(str)
    offset = @heap_offset
    str.chars.each_with_index do |ch, idx|
      @output_lines << "    PUSH #{offset + idx}"
      @output_lines << "    PUSH #{ch.ord}"
      @output_lines << "    STORE_HEAP"
    end
    @output_lines << "    PUSH #{offset + str.length}"
    @output_lines << "    PUSH 0"
    @output_lines << "    STORE_HEAP"
    @heap_offset = offset + str.length + 1
    offset
  end
end